os: Visual Studio 2019
configuration: Release
platform: Any CPU

version: '1.2.{build}'
skip_tags: true

build:
  project: ClipboardMachinery\ClipboardMachinery.sln
  verbosity: minimal

install:
  cmd: git submodule -q update --init  

before_build:
  cmd: nuget restore ClipboardMachinery\ClipboardMachinery.sln

assembly_info:
  patch: true
  file: ClipboardMachinery\ClipboardMachinery\Properties\AssemblyInfo.cs
  assembly_version: '{version}'

artifacts:
  path: ClipboardMachinery\ClipboardMachinery\bin\Release
  name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)
  type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: O41NF5QmjIQEBgMrqkh+/k88YnPmao8ZXj2p4WcTFVZ+CTW7WERbsZqokwnAsk6H
  release: $(APPVEYOR_PROJECT_NAME) $(APPVEYOR_BUILD_VERSION)
  tag: $(APPVEYOR_BUILD_VERSION)
  draft: true
  prerelease: false
  on:
    branch: master